vaadin.launch-browser=true
spring.application.name=backend_utenti


spring.datasource.url=jdbc:postgresql://localhost:5432/smartshift_db
spring.datasource.username=postgres
spring.datasource.password=pippo123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


smartshift.app.jwtSecret=SuperSecretKeyPerFirmaTokenJWTMinimo32Caratteri
smartshift.app.jwtExpirationMs=86400000
